### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by franzitobambino** [ako-v/cra-tailwind-jit#1]
Hey,
I used the clone and ran npm run dev and got he following message in bash:
concurrently "npm run watch" "npm run start"

'concurrently' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cra-tailwind-jit@0.1.0 dev: `concurrently "npm run watch" "npm run start"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cra-tailwind-jit@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
I am probably doing something wrong - LMK

**Comment by franzitobambino** [comment]
I looked at the official guide and it seems as though i need to replace all react-scripts with craco except for the eject script.
      "start": "craco start",
     "build": "craco build",
     "test": "craco test",

**Comment by ako-v** [comment]
Hi. Have you ran `npm install` after you cloned the project?
if not, please first run : `npm install` and after that use npm start or whatever you want. because you need to install necessary packages in order to be able to use them.
